language: groovy
sudo: required
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
jdk:
- openjdk8
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 3q37jIBy+3hAFXRbKuLf7+gOGm1YSiTCA/cCqkefbQBZW9bfurXdaw69R55ZR81xnbQ6/EtzZqgCjTDgL016qmkdem27Jk9VAvMtM61pQrX78JUeXioG6rlYj4OOGk3D3e+b5PMSzaL5GEu8T0VIVEw5dKWffziIIa2pD9gAXWoZpuwgUyK5NQS+fEnB7Rla0DKz7RcVeXcBViXO4I0VMyWHIsafSFo/YAgTvyvoYzcBNrJRXgoYAAHX8jTTgmd+EkIvu+jAK73ZjPY3RvMSbDH2vh07+ozb80fw6NdEszFMAwr5Q9y68AMzhyhZAk52Z1jwJaf8Q71viLL2ociQ/cxxqsOCociioX/2ZMKv91F8lbWfKWZxguTrsg59Vk8mqIji7hsXPBNNZyD0m+12DikpAMVW2sYpSADmL2Px0/YrEP0aWbyDW6IOt6CM+Z+YZy9e+LsLLYsAHqXZhgJXusgKCLD7I6gxQ1jcQ8APseEFcIKc8Hqp3h46eRH/wt9nExzG/DNIEhBCLe9YoG00IjlBHu8qLj/Mzgc51bYHRLBdGe66DlFEljlQ9G3AUNvYHETWkrfkyMHEL8jh7twQn0SRQRvfmqz3N/45qlPzRUiWfsnE35bMiFfo2kc16pVYY4dRtAjUrHYUwNDbuJZhEx/gTN9HjYq6RAL7jwYfVQw=
  file: build/libs/RoddyToolLib-*.jar
  file_glob: true
  on:
    repo: TheRoddyWMS/RoddyToolLib
    branch: master
    tags: true
  overwrite: true
